name: Build and publish

on:
  workflow_dispatch:
  schedule:
  - cron: "22 3 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Publish Edition as GitHub Pages Website
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx6g
      TYPESENSE_HOST: typesense.acdh-dev.oeaw.ac.at
      TYPESENSE_PORT: 443
      TYPESENSE_PROTOCOL: https
      TYPESENSE_API_KEY: ${{secrets.TYPESENSE_API_KEY}}
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'
    - name: Install Saxon, Ant and Python
      run: |
        sudo apt-get update && sudo apt-get install texlive-xetex texlive-humanities texlive-lang-german texlive-lang-french texlive-lang-english texlive-lang-greek fonts-freefont-ttf fonts-dejavu texlive-fonts-recommended openjdk-11-jre-headless ant -y
        ./shellscripts/dl_saxon.sh
        pip install -r requirements.txt
    - name: Fetch data
      run: ./fetch_data.sh
    - name: Process Data
      run: ./process.sh
    # - name: Fulltext Index
    #   run: python3 make_ts_index.py
    - name: Build
      run: ant
    - name: make pdfs
      run: ./make_pdf.sh
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: './html'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
